# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e81071eacc4e6023dcc69942d1cb580"
application_url = "https://distance-distributors-revenue-mpg.trycloudflare.com"
embedded = true
name = "PortalSphere"
handle = "portalsphere-3"

[build]
include_config_on_deploy = true
dev_store_url = "portalspheredev.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://distance-distributors-revenue-mpg.trycloudflare.com/auth/callback",
  "https://distance-distributors-revenue-mpg.trycloudflare.com/auth/shopify/callback",
  "https://distance-distributors-revenue-mpg.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
